/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bdc141e8-a3f8-4b47-b3ad-2f47837f5813",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OuYFPSSg7",
    "aws_user_pools_web_client_id": "3ipp7uglgh4j1he5324sqdaa9a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ioach4smzfd5pjxakldyms7jxi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
